# Generated by Django 4.2.18 on 2025-01-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(verbose_name='Номер стола')),
                ('order_id', models.CharField(max_length=10, unique=True, verbose_name='ID заказа')),
                ('items', models.TextField(verbose_name='Заказанные блюда')),
                ('status', models.CharField(default='в ожидании', max_length=20, verbose_name='Статус')),
            ],
        ),
    ]
