# Generated by Django 4.2.18 on 2025-02-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_parsed',
            field=models.JSONField(default=list, verbose_name='Разобранные данные заказа'),
        ),
    ]
